# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from protos import bank_pb2 as protos_dot_bank__pb2


class bankStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.confirmTransaction = channel.unary_unary(
                '/bank.bank/confirmTransaction',
                request_serializer=protos_dot_bank__pb2.PispRequest.SerializeToString,
                response_deserializer=protos_dot_bank__pb2.PispReply.FromString,
                )
        self.getNonce = channel.unary_unary(
                '/bank.bank/getNonce',
                request_serializer=protos_dot_bank__pb2.NonceRequest.SerializeToString,
                response_deserializer=protos_dot_bank__pb2.NonceReply.FromString,
                )


class bankServicer(object):
    """Missing associated documentation comment in .proto file."""

    def confirmTransaction(self, request, context):
        """server back reply.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getNonce(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_bankServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'confirmTransaction': grpc.unary_unary_rpc_method_handler(
                    servicer.confirmTransaction,
                    request_deserializer=protos_dot_bank__pb2.PispRequest.FromString,
                    response_serializer=protos_dot_bank__pb2.PispReply.SerializeToString,
            ),
            'getNonce': grpc.unary_unary_rpc_method_handler(
                    servicer.getNonce,
                    request_deserializer=protos_dot_bank__pb2.NonceRequest.FromString,
                    response_serializer=protos_dot_bank__pb2.NonceReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'bank.bank', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class bank(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def confirmTransaction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/bank.bank/confirmTransaction',
            protos_dot_bank__pb2.PispRequest.SerializeToString,
            protos_dot_bank__pb2.PispReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def getNonce(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/bank.bank/getNonce',
            protos_dot_bank__pb2.NonceRequest.SerializeToString,
            protos_dot_bank__pb2.NonceReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
