# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/bank.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='protos/bank.proto',
  package='bank',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x11protos/bank.proto\x12\x04\x62\x61nk\"\x80\x01\n\x0bPispRequest\x12#\n\x05nonce\x18\x01 \x01(\x0b\x32\x14.bank.EncryptedNonce\x12!\n\x04\x64\x61ta\x18\x02 \x01(\x0b\x32\x13.bank.EncryptedData\x12\r\n\x05token\x18\x03 \x01(\t\x12\x0c\n\x04iban\x18\x04 \x01(\t\x12\x0c\n\x04name\x18\x05 \x01(\t\"S\n\x0e\x45ncryptedNonce\x12\x13\n\x0bhashedNonce\x18\x01 \x01(\t\x12\x16\n\x0e\x65ncryptedNonce\x18\x02 \x01(\t\x12\x14\n\x0c\x65ncryptedKey\x18\x03 \x01(\t\"P\n\rEncryptedData\x12\x12\n\nhashedData\x18\x01 \x01(\t\x12\x15\n\rencryptedData\x18\x02 \x01(\t\x12\x14\n\x0c\x65ncryptedKey\x18\x03 \x01(\t\"\x1b\n\tPispReply\x12\x0e\n\x06status\x18\x01 \x01(\t\"\x1d\n\x0cNonceRequest\x12\r\n\x05token\x18\x01 \x01(\t\"\x1b\n\nNonceReply\x12\r\n\x05nonce\x18\x01 \x01(\t2v\n\x04\x62\x61nk\x12:\n\x12\x63onfirmTransaction\x12\x11.bank.PispRequest\x1a\x0f.bank.PispReply\"\x00\x12\x32\n\x08getNonce\x12\x12.bank.NonceRequest\x1a\x10.bank.NonceReply\"\x00\x62\x06proto3'
)




_PISPREQUEST = _descriptor.Descriptor(
  name='PispRequest',
  full_name='bank.PispRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='nonce', full_name='bank.PispRequest.nonce', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data', full_name='bank.PispRequest.data', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='token', full_name='bank.PispRequest.token', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='iban', full_name='bank.PispRequest.iban', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='bank.PispRequest.name', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=156,
)


_ENCRYPTEDNONCE = _descriptor.Descriptor(
  name='EncryptedNonce',
  full_name='bank.EncryptedNonce',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='hashedNonce', full_name='bank.EncryptedNonce.hashedNonce', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='encryptedNonce', full_name='bank.EncryptedNonce.encryptedNonce', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='encryptedKey', full_name='bank.EncryptedNonce.encryptedKey', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=158,
  serialized_end=241,
)


_ENCRYPTEDDATA = _descriptor.Descriptor(
  name='EncryptedData',
  full_name='bank.EncryptedData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='hashedData', full_name='bank.EncryptedData.hashedData', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='encryptedData', full_name='bank.EncryptedData.encryptedData', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='encryptedKey', full_name='bank.EncryptedData.encryptedKey', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=243,
  serialized_end=323,
)


_PISPREPLY = _descriptor.Descriptor(
  name='PispReply',
  full_name='bank.PispReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='bank.PispReply.status', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=325,
  serialized_end=352,
)


_NONCEREQUEST = _descriptor.Descriptor(
  name='NonceRequest',
  full_name='bank.NonceRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='token', full_name='bank.NonceRequest.token', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=354,
  serialized_end=383,
)


_NONCEREPLY = _descriptor.Descriptor(
  name='NonceReply',
  full_name='bank.NonceReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='nonce', full_name='bank.NonceReply.nonce', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=385,
  serialized_end=412,
)

_PISPREQUEST.fields_by_name['nonce'].message_type = _ENCRYPTEDNONCE
_PISPREQUEST.fields_by_name['data'].message_type = _ENCRYPTEDDATA
DESCRIPTOR.message_types_by_name['PispRequest'] = _PISPREQUEST
DESCRIPTOR.message_types_by_name['EncryptedNonce'] = _ENCRYPTEDNONCE
DESCRIPTOR.message_types_by_name['EncryptedData'] = _ENCRYPTEDDATA
DESCRIPTOR.message_types_by_name['PispReply'] = _PISPREPLY
DESCRIPTOR.message_types_by_name['NonceRequest'] = _NONCEREQUEST
DESCRIPTOR.message_types_by_name['NonceReply'] = _NONCEREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PispRequest = _reflection.GeneratedProtocolMessageType('PispRequest', (_message.Message,), {
  'DESCRIPTOR' : _PISPREQUEST,
  '__module__' : 'protos.bank_pb2'
  # @@protoc_insertion_point(class_scope:bank.PispRequest)
  })
_sym_db.RegisterMessage(PispRequest)

EncryptedNonce = _reflection.GeneratedProtocolMessageType('EncryptedNonce', (_message.Message,), {
  'DESCRIPTOR' : _ENCRYPTEDNONCE,
  '__module__' : 'protos.bank_pb2'
  # @@protoc_insertion_point(class_scope:bank.EncryptedNonce)
  })
_sym_db.RegisterMessage(EncryptedNonce)

EncryptedData = _reflection.GeneratedProtocolMessageType('EncryptedData', (_message.Message,), {
  'DESCRIPTOR' : _ENCRYPTEDDATA,
  '__module__' : 'protos.bank_pb2'
  # @@protoc_insertion_point(class_scope:bank.EncryptedData)
  })
_sym_db.RegisterMessage(EncryptedData)

PispReply = _reflection.GeneratedProtocolMessageType('PispReply', (_message.Message,), {
  'DESCRIPTOR' : _PISPREPLY,
  '__module__' : 'protos.bank_pb2'
  # @@protoc_insertion_point(class_scope:bank.PispReply)
  })
_sym_db.RegisterMessage(PispReply)

NonceRequest = _reflection.GeneratedProtocolMessageType('NonceRequest', (_message.Message,), {
  'DESCRIPTOR' : _NONCEREQUEST,
  '__module__' : 'protos.bank_pb2'
  # @@protoc_insertion_point(class_scope:bank.NonceRequest)
  })
_sym_db.RegisterMessage(NonceRequest)

NonceReply = _reflection.GeneratedProtocolMessageType('NonceReply', (_message.Message,), {
  'DESCRIPTOR' : _NONCEREPLY,
  '__module__' : 'protos.bank_pb2'
  # @@protoc_insertion_point(class_scope:bank.NonceReply)
  })
_sym_db.RegisterMessage(NonceReply)



_BANK = _descriptor.ServiceDescriptor(
  name='bank',
  full_name='bank.bank',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=414,
  serialized_end=532,
  methods=[
  _descriptor.MethodDescriptor(
    name='confirmTransaction',
    full_name='bank.bank.confirmTransaction',
    index=0,
    containing_service=None,
    input_type=_PISPREQUEST,
    output_type=_PISPREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='getNonce',
    full_name='bank.bank.getNonce',
    index=1,
    containing_service=None,
    input_type=_NONCEREQUEST,
    output_type=_NONCEREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_BANK)

DESCRIPTOR.services_by_name['bank'] = _BANK

# @@protoc_insertion_point(module_scope)
