# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: backend/server.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='backend/server.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x14\x62\x61\x63kend/server.proto\"f\n\x0bPaymentInfo\x12\x1e\n\x05nonce\x18\x01 \x01(\x0b\x32\x0f.EncryptedNonce\x12\x1c\n\x04\x64\x61ta\x18\x02 \x01(\x0b\x32\x0e.EncryptedData\x12\x19\n\x05token\x18\x03 \x01(\x0b\x32\n.UserToken\"S\n\x0e\x45ncryptedNonce\x12\x13\n\x0bhashedNonce\x18\x01 \x01(\t\x12\x16\n\x0e\x65ncryptedNonce\x18\x02 \x01(\t\x12\x14\n\x0c\x65ncryptedKey\x18\x03 \x01(\t\"P\n\rEncryptedData\x12\x12\n\nhashedData\x18\x01 \x01(\t\x12\x15\n\rencryptedData\x18\x02 \x01(\t\x12\x14\n\x0c\x65ncryptedKey\x18\x03 \x01(\t\"0\n\tUserToken\x12\r\n\x05token\x18\x01 \x01(\t\x12\x14\n\x0cmerchantName\x18\x02 \x01(\t\"\x16\n\x05Nonce\x12\r\n\x05nonce\x18\x01 \x01(\t\"\x12\n\x03URL\x12\x0b\n\x03url\x18\x01 \x01(\t\"\x1e\n\x0c\x43onfirmation\x12\x0e\n\x06status\x18\x01 \x01(\t2\x85\x01\n\tPIService\x12 \n\x08getNonce\x12\n.UserToken\x1a\x06.Nonce\"\x00\x12\"\n\nrequestURL\x12\x0c.PaymentInfo\x1a\x04.URL\"\x00\x12\x32\n\x13requestConfirmation\x12\n.UserToken\x1a\r.Confirmation\"\x00\x62\x06proto3'
)




_PAYMENTINFO = _descriptor.Descriptor(
  name='PaymentInfo',
  full_name='PaymentInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='nonce', full_name='PaymentInfo.nonce', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data', full_name='PaymentInfo.data', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='token', full_name='PaymentInfo.token', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=126,
)


_ENCRYPTEDNONCE = _descriptor.Descriptor(
  name='EncryptedNonce',
  full_name='EncryptedNonce',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='hashedNonce', full_name='EncryptedNonce.hashedNonce', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='encryptedNonce', full_name='EncryptedNonce.encryptedNonce', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='encryptedKey', full_name='EncryptedNonce.encryptedKey', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=128,
  serialized_end=211,
)


_ENCRYPTEDDATA = _descriptor.Descriptor(
  name='EncryptedData',
  full_name='EncryptedData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='hashedData', full_name='EncryptedData.hashedData', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='encryptedData', full_name='EncryptedData.encryptedData', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='encryptedKey', full_name='EncryptedData.encryptedKey', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=213,
  serialized_end=293,
)


_USERTOKEN = _descriptor.Descriptor(
  name='UserToken',
  full_name='UserToken',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='token', full_name='UserToken.token', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='merchantName', full_name='UserToken.merchantName', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=295,
  serialized_end=343,
)


_NONCE = _descriptor.Descriptor(
  name='Nonce',
  full_name='Nonce',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='nonce', full_name='Nonce.nonce', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=345,
  serialized_end=367,
)


_URL = _descriptor.Descriptor(
  name='URL',
  full_name='URL',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='url', full_name='URL.url', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=369,
  serialized_end=387,
)


_CONFIRMATION = _descriptor.Descriptor(
  name='Confirmation',
  full_name='Confirmation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='Confirmation.status', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=389,
  serialized_end=419,
)

_PAYMENTINFO.fields_by_name['nonce'].message_type = _ENCRYPTEDNONCE
_PAYMENTINFO.fields_by_name['data'].message_type = _ENCRYPTEDDATA
_PAYMENTINFO.fields_by_name['token'].message_type = _USERTOKEN
DESCRIPTOR.message_types_by_name['PaymentInfo'] = _PAYMENTINFO
DESCRIPTOR.message_types_by_name['EncryptedNonce'] = _ENCRYPTEDNONCE
DESCRIPTOR.message_types_by_name['EncryptedData'] = _ENCRYPTEDDATA
DESCRIPTOR.message_types_by_name['UserToken'] = _USERTOKEN
DESCRIPTOR.message_types_by_name['Nonce'] = _NONCE
DESCRIPTOR.message_types_by_name['URL'] = _URL
DESCRIPTOR.message_types_by_name['Confirmation'] = _CONFIRMATION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PaymentInfo = _reflection.GeneratedProtocolMessageType('PaymentInfo', (_message.Message,), {
  'DESCRIPTOR' : _PAYMENTINFO,
  '__module__' : 'backend.server_pb2'
  # @@protoc_insertion_point(class_scope:PaymentInfo)
  })
_sym_db.RegisterMessage(PaymentInfo)

EncryptedNonce = _reflection.GeneratedProtocolMessageType('EncryptedNonce', (_message.Message,), {
  'DESCRIPTOR' : _ENCRYPTEDNONCE,
  '__module__' : 'backend.server_pb2'
  # @@protoc_insertion_point(class_scope:EncryptedNonce)
  })
_sym_db.RegisterMessage(EncryptedNonce)

EncryptedData = _reflection.GeneratedProtocolMessageType('EncryptedData', (_message.Message,), {
  'DESCRIPTOR' : _ENCRYPTEDDATA,
  '__module__' : 'backend.server_pb2'
  # @@protoc_insertion_point(class_scope:EncryptedData)
  })
_sym_db.RegisterMessage(EncryptedData)

UserToken = _reflection.GeneratedProtocolMessageType('UserToken', (_message.Message,), {
  'DESCRIPTOR' : _USERTOKEN,
  '__module__' : 'backend.server_pb2'
  # @@protoc_insertion_point(class_scope:UserToken)
  })
_sym_db.RegisterMessage(UserToken)

Nonce = _reflection.GeneratedProtocolMessageType('Nonce', (_message.Message,), {
  'DESCRIPTOR' : _NONCE,
  '__module__' : 'backend.server_pb2'
  # @@protoc_insertion_point(class_scope:Nonce)
  })
_sym_db.RegisterMessage(Nonce)

URL = _reflection.GeneratedProtocolMessageType('URL', (_message.Message,), {
  'DESCRIPTOR' : _URL,
  '__module__' : 'backend.server_pb2'
  # @@protoc_insertion_point(class_scope:URL)
  })
_sym_db.RegisterMessage(URL)

Confirmation = _reflection.GeneratedProtocolMessageType('Confirmation', (_message.Message,), {
  'DESCRIPTOR' : _CONFIRMATION,
  '__module__' : 'backend.server_pb2'
  # @@protoc_insertion_point(class_scope:Confirmation)
  })
_sym_db.RegisterMessage(Confirmation)



_PISERVICE = _descriptor.ServiceDescriptor(
  name='PIService',
  full_name='PIService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=422,
  serialized_end=555,
  methods=[
  _descriptor.MethodDescriptor(
    name='getNonce',
    full_name='PIService.getNonce',
    index=0,
    containing_service=None,
    input_type=_USERTOKEN,
    output_type=_NONCE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='requestURL',
    full_name='PIService.requestURL',
    index=1,
    containing_service=None,
    input_type=_PAYMENTINFO,
    output_type=_URL,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='requestConfirmation',
    full_name='PIService.requestConfirmation',
    index=2,
    containing_service=None,
    input_type=_USERTOKEN,
    output_type=_CONFIRMATION,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_PISERVICE)

DESCRIPTOR.services_by_name['PIService'] = _PISERVICE

# @@protoc_insertion_point(module_scope)
